### ISSUE TITLE
Keypress Entry

### ISSUE THREAD

**Issue by theryjo** [monkeytypegame/monkeytype-fingermap#2]
Thoughts on extending this to allow keypress entry?
Idea would be:
- Keypress fills key with current color
- 'Space' key (or other) toggles current selected color

**Comment by Miodec** [comment]
You can already switch "fingers" by pressing 1-0. Highlighting keys with keypresses shouldnt be too hard.

**Comment by theryjo** [comment]
Prototyped an impl at: https://github.com/theryjo/fingermap/tree/prototype-keypress (mentioned in discord).
https://teal-tamqrah-6.tiiny.site/ (demo)

I modified finger switching as the 1-10 key finger switching collides with entry of the 1-10 keys into the map. An alternative solution that removes conflicts for 'space' and 'shift' keys might involve key combinations like 'shift-1' or 'shift-space' for finger switching. Under this solution, a non-combo  shift press would fill in the map as with any other key.

**Comment by theryjo** [comment]
Copy of discord feedback:

"i think i would drop the shift + key functionality, and have it always be multi selection
and also if a key is already highlighted, pressing that key again with remove it
space for next finger seems unintuitive to me
i think we could even invert multi mode
so that holding shift is override mode
since mutli will be more used
then mouse and keyboard input will be in sync"

"do both keyboard and mouse selection
oh wait, you mean finger selection
i think just leave it on the mouse for now"

"nice thanks
the whole fingermap page should be redone to fit more with the style 
something like https://events.monkeytype.com/
is way closer in style to mt
but thats for another time"
